[package]
name = "topiks"
version = "0.1.0-alpha+001"
authors = ["Sean Policarpio <sean@policarp.io>"]

[dependencies]
byteorder = "1.2.1"
termion = "1.5.1"
clap = "2.31.2"

[dev-dependencies]
proptest = "0.8.7"

